const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Shirt',
      slug: 'free-shirt',
      isFeatured: true,
      featurdImage: '/images/shirt1.jpg',
    },
    {
      name: 'Fit Shirt',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Addidas',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Shirt',
      slug: 'fit-shirt',
      isFeatured: true,
      featurdImage: '/images/shirt2.jpg',
    },
    {
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Shirts',
      slug: 'slim-shirt',
      isFeatured: true,
      featurdImage: '/images/shirt3.jpg',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Pants',
      slug: 'golf-pants',
    },
    {
      name: 'fit Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 50,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Pants',
      slug: 'fit-pants',
    },
    {
      name: 'Chust Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Chust',
      rating: 2.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Chust Pants',
      slug: 'chust-pants',
    },
  ],
};

export default data;
